name: Developer Task
description: Create a new developer task
title: "[Task] "
labels: ["task", "development"]
body:
  - type: markdown
    attributes:
      value: |
        ## Developer Task Details
        Please provide the details for this development task.

  - type: input
    id: related-user-story
    attributes:
      label: Related User Story
      description: If this task is derived from a user story, provide the link or ID
      placeholder: "#123"
    validations:
      required: false

  - type: textarea
    id: description
    attributes:
      label: Task Description
      description: Provide a detailed description of what needs to be implemented
      placeholder: "Implement feature X with the following requirements..."
    validations:
      required: true

  - type: textarea
    id: technical-details
    attributes:
      label: Technical Details
      description: Provide any technical details, architecture decisions, or implementation notes
      placeholder: |
        - Technical approach
        - Components to modify
        - API endpoints to create/modify
    validations:
      required: false

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: List the criteria that must be met for this task to be considered complete
      placeholder: |
        - [ ] Criteria 1
        - [ ] Criteria 2
        - [ ] Criteria 3
    validations:
      required: true

  - type: textarea
    id: testing-notes
    attributes:
      label: Testing Notes
      description: Describe how this task should be tested
      placeholder: |
        - Unit tests for...
        - Integration tests for...
        - Manual testing steps...
    validations:
      required: false

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: Select the priority level for this task
      options:
        - Low
        - Medium
        - High
        - Critical
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or information about the task
    validations:
      required: false
