name: User Story
description: Create a new user story
title: "As a [role], I want to [capability], so that [benefit]"
labels: ["user-story"]
body:
  - type: markdown
    attributes:
      value: |
        ## User Story Details
        Please provide the details for this user story.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Provide a detailed description of the user story
      placeholder: "As a [role], I want to [capability], so that [benefit]"
    validations:
      required: true

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: List the criteria that must be met for this story to be considered complete
      placeholder: |
        - [ ] Criteria 1
        - [ ] Criteria 2
        - [ ] Criteria 3
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or information about the user story
    validations:
      required: false
