name: checks
on:
  push:
  pull_request:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 23.x # Ensure this matches the version in package.json
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 10
      - run: pnpm install
      - run: pnpx eslint .
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 23.x # Ensure this matches the version in package.json
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 10
      - run: pnpm install
      - run: pnpx prettier . --check
