name: CI
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Install modules
        run: pnpm install
      - name: Run ESLint
        run: eslint .
