name: Lint
on: push
jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8.15

      - run: pnpm install
      - run: pnpm run lint
